Parameters:
  vfsID:
    Type: String
  sgID:
    Type: String
  fileSystemId:
    Type: String
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]
Resources:
  VfsAccessPoint7547BE94:
    Type: AWS::EFS::AccessPoint
    Properties:
      AccessPointTags:
        - Key: Name
          Value: EfsBasicStack/VfsAccessPoint
      FileSystemId:
        Ref: fileSystemId
      PosixUser:
        Gid: "0"
        Uid: "0"
      RootDirectory:
        CreationInfo:
          OwnerGid: "0"
          OwnerUid: "0"
          Permissions: "777"
        Path:
          Fn::Join:
            - ""
            - - /
              - Ref: vfsID
    Metadata:
      aws:cdk:path: EfsBasicStack/VfsAccessPoint/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/zPSMzQy0zNQTCwv1k1OydbNyUzSqw4uSUzO1nFOywtILErMTS1JLdIJSi3OLy1KTtUBKoxPTSvWq3ZMTk4tLg7Iz8wrASlF4taC+P6lJQWlYBmY1lqdgMqSjPw8fWM9Q0M9c8Ws4sxM3aLSvJLM3FS9IAgNAB2jnKKPAAAA
    Metadata:
      aws:cdk:path: EfsBasicStack/CDKMetadata/Default
Outputs:
  AccessPointId:
    Value:
      Ref: VfsAccessPoint7547BE94
Rules:
  CheckBootstrapVersion:
    Assertions:
      - Assert:
          Fn::Not:
            - Fn::Contains:
                - - "1"
                  - "2"
                  - "3"
                  - "4"
                  - "5"
                - Ref: BootstrapVersion
        AssertDescription: CDK bootstrap stack version 6 required. Please run 'cdk bootstrap' with a recent version of the CDK CLI.

